### ISSUE TITLE
Make log string customizable

### ISSUE THREAD

**Issue by eloyesp** [akempes/laravel-request-logging#11]
It would be great to have some way to configure the log strings to fit better on the context... for example: for heroku the `timestamp` part is irrelevant (as heroku timestamps logs anyway) and a way to add the [request-id](https://devcenter.heroku.com/articles/http-request-id) could help matching the request with the response.

I'm not sure how to implement placeholders on php (I'm not a php developer), but I think something like this would work:

``` php
/* config/ request-logging.php */
[
  'request-log-string':   'IP: {ip} {startedAt} {method} {uri} {bodyAsJson} files: {files}',
  'response-log-string': 'User: {userId} {status} - Duration: {duration}ms - Body: {bodyAsJson} {redirect}',
];
```

Hope it makes sense, and thanks for this great library.

**Comment by akempes** [comment]
Thanks for your feedback! It's sure a good addition to this library which wouldn't be too hard to implement. 
I'm on holiday right now but when I'm back I will make some time to implement your request.

It's not perfect, but you can match the request and response by the number after the #. I will reviews this as well.

**Comment by akempes** [comment]
An update has been issued. Check the readme to find all available variables.
